name: Repository creation
description: Create a repository in AICoE Org
title: "CREATE: <repo_name>"
labels: [bug, triage]
assignees:
  - octocat
body:
- type: markdown
  attributes:
    value: |
      # Who should have admin access
      e.g. alice, bob

      # Who should have write access
      e.g. chris, dianne

      # What should the repo description be
      by default we will set it to "created due to (link to this issue)"

      # Additional context for request
      Any additional information or context to describe the request.
- type: textarea
  id: new-repo
  attributes:
    label: New Repository
    description: new repository name
    placeholder: repository name
  validations:
    required: true
