name: Repository creation
description: Create a repository in AICoE Org
title: "CREATE: <repo_name>"
labels: [bug, triage]
assignees:
  - octocat
body:
- type: markdown
  attributes:
    value: |
      # New Repository
      e.g. new repository

      # Requested name for new repository
      e.g. foo

      # Who should have admin access
      e.g. alice, bob

      # Who should have write access
      e.g. chris, dianne

      # What should the repo description be
      by default we will set it to "created due to (link to this issue)"

      # Additional context for request
      Any additional information or context to describe the request.


