name: Repository creation
description: Create a repository in AICoE Org
title: "CREATE: <repo_name>"
labels: [kind/question]
assignees:
  - tumido
  - goern
body:
- type: textarea
  id: new-repo
  attributes:
    label: New Repository
    description: new repository name
    placeholder: repository name
  validations:
    required: true
- type: textarea
  id: repo-desc
  attributes:
    label: What should the repo description be
    description: What should the repo description be
    placeholder: What should the repo description be
  validations:
    required: true
- type: textarea
  id: write-access
  attributes:
    label: Who should have write access
    description: Who should have write access
    placeholder: userid, userid
  validations:
    required: true
- type: textarea
  id: admin-access
  attributes:
    label: Who should have admin access
    description: Who should have admin access
    placeholder: userid, userid
  validations:
    required: true
